
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  AppInput: typeof import("../../app/components/AppComponents/AppInput.vue")['default']
  FormDateInput: typeof import("../../app/components/AppComponents/FormDateInput.vue")['default']
  HeaderCompetition: typeof import("../../app/components/AppComponents/HeaderCompetition.vue")['default']
  Loader: typeof import("../../app/components/AppComponents/Loader.vue")['default']
  SearchBar: typeof import("../../app/components/AppComponents/SearchBar.vue")['default']
  AppFooter: typeof import("../../app/components/AppFooter.vue")['default']
  AuthFooter: typeof import("../../app/components/Auth/AuthFooter.vue")['default']
  AuthForm: typeof import("../../app/components/Auth/AuthForm.vue")['default']
  AuthHero: typeof import("../../app/components/Auth/AuthHero.vue")['default']
  AuthSocial: typeof import("../../app/components/Auth/AuthSocial.vue")['default']
  ProfileEmpty: typeof import("../../app/components/Profile/ProfileEmpty.vue")['default']
  ProfileHero: typeof import("../../app/components/Profile/ProfileHero.vue")['default']
  ProfileHistory: typeof import("../../app/components/Profile/ProfileHistory.vue")['default']
  ProfileInfo: typeof import("../../app/components/Profile/ProfileInfo.vue")['default']
  AdminTaskControls: typeof import("../../app/components/Tasks/AdminTaskControls.vue")['default']
  CreateTaskModal: typeof import("../../app/components/Tasks/CreateTaskModal.vue")['default']
  TaskAdminPanel: typeof import("../../app/components/Tasks/TaskAdminPanel.vue")['default']
  TaskCard: typeof import("../../app/components/Tasks/TaskCard.vue")['default']
  TaskDetailHero: typeof import("../../app/components/Tasks/TaskDetailHero.vue")['default']
  TaskSidebar: typeof import("../../app/components/Tasks/TaskSidebar.vue")['default']
  TaskSubmissionForm: typeof import("../../app/components/Tasks/TaskSubmissionForm.vue")['default']
  TasksHero: typeof import("../../app/components/Tasks/TasksHero.vue")['default']
  CreateTeamModal: typeof import("../../app/components/Teams/CreateTeamModal.vue")['default']
  EditTeamModal: typeof import("../../app/components/Teams/EditTeamModal.vue")['default']
  TeamCard: typeof import("../../app/components/Teams/TeamCard.vue")['default']
  LanguageSwitcher: typeof import("../../app/components/shared/LanguageSwitcher.vue")['default']
  CreateTournamentModal: typeof import("../../app/components/tournaments/CreateTournamentModal.vue")['default']
  TournamentAbout: typeof import("../../app/components/tournaments/Detail/TournamentAbout.vue")['default']
  TournamentTeamsSection: typeof import("../../app/components/tournaments/Detail/TournamentTeamsSection.vue")['default']
  EditTournamentModal: typeof import("../../app/components/tournaments/EditTournamentModal.vue")['default']
  TournamentBracket: typeof import("../../app/components/tournaments/TournamentBracket.vue")['default']
  TournamentCard: typeof import("../../app/components/tournaments/TournamentCard.vue")['default']
  TournamentHero: typeof import("../../app/components/tournaments/TournamentHero.vue")['default']
  TournamentInfo: typeof import("../../app/components/tournaments/TournamentInfo.vue")['default']
  TournamentJuryManager: typeof import("../../app/components/tournaments/TournamentJuryManager.vue")['default']
  TournamentSidebar: typeof import("../../app/components/tournaments/TournamentSidebar.vue")['default']
  TournamentStats: typeof import("../../app/components/tournaments/TournamentStats.vue")['default']
  TournamentTeamsTable: typeof import("../../app/components/tournaments/TournamentTeamsTable.vue")['default']
  TournamentsList: typeof import("../../app/components/tournaments/TournamentsList.vue")['default']
  DeleteModal: typeof import("../../app/components/tournaments/deleteModal.vue")['default']
  NuxtWelcome: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtAnnouncer: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
  NuxtImg: typeof import("../../../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.15.3__ioredis@5.10.1_magicast@0.5.2/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  NuxtPicture: typeof import("../../../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.15.3__ioredis@5.10.1_magicast@0.5.2/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  AutoComplete: typeof import("primevue/autocomplete")['default']
  Calendar: typeof import("primevue/calendar")['default']
  CascadeSelect: typeof import("primevue/cascadeselect")['default']
  Checkbox: typeof import("primevue/checkbox")['default']
  CheckboxGroup: typeof import("primevue/checkboxgroup")['default']
  Chips: typeof import("primevue/chips")['default']
  ColorPicker: typeof import("primevue/colorpicker")['default']
  DatePicker: typeof import("primevue/datepicker")['default']
  Dropdown: typeof import("primevue/dropdown")['default']
  FloatLabel: typeof import("primevue/floatlabel")['default']
  Fluid: typeof import("primevue/fluid")['default']
  IconField: typeof import("primevue/iconfield")['default']
  IftaLabel: typeof import("primevue/iftalabel")['default']
  InputChips: typeof import("primevue/inputchips")['default']
  InputGroup: typeof import("primevue/inputgroup")['default']
  InputGroupAddon: typeof import("primevue/inputgroupaddon")['default']
  InputIcon: typeof import("primevue/inputicon")['default']
  InputMask: typeof import("primevue/inputmask")['default']
  InputNumber: typeof import("primevue/inputnumber")['default']
  InputOtp: typeof import("primevue/inputotp")['default']
  InputSwitch: typeof import("primevue/inputswitch")['default']
  InputText: typeof import("primevue/inputtext")['default']
  Knob: typeof import("primevue/knob")['default']
  Listbox: typeof import("primevue/listbox")['default']
  MultiSelect: typeof import("primevue/multiselect")['default']
  Password: typeof import("primevue/password")['default']
  RadioButton: typeof import("primevue/radiobutton")['default']
  RadioButtonGroup: typeof import("primevue/radiobuttongroup")['default']
  Rating: typeof import("primevue/rating")['default']
  Select: typeof import("primevue/select")['default']
  SelectButton: typeof import("primevue/selectbutton")['default']
  Slider: typeof import("primevue/slider")['default']
  Textarea: typeof import("primevue/textarea")['default']
  ToggleButton: typeof import("primevue/togglebutton")['default']
  ToggleSwitch: typeof import("primevue/toggleswitch")['default']
  TreeSelect: typeof import("primevue/treeselect")['default']
  Button: typeof import("primevue/button")['default']
  ButtonGroup: typeof import("primevue/buttongroup")['default']
  SpeedDial: typeof import("primevue/speeddial")['default']
  SplitButton: typeof import("primevue/splitbutton")['default']
  Column: typeof import("primevue/column")['default']
  Row: typeof import("primevue/row")['default']
  ColumnGroup: typeof import("primevue/columngroup")['default']
  DataTable: typeof import("primevue/datatable")['default']
  DataView: typeof import("primevue/dataview")['default']
  OrderList: typeof import("primevue/orderlist")['default']
  OrganizationChart: typeof import("primevue/organizationchart")['default']
  Paginator: typeof import("primevue/paginator")['default']
  PickList: typeof import("primevue/picklist")['default']
  Tree: typeof import("primevue/tree")['default']
  TreeTable: typeof import("primevue/treetable")['default']
  Timeline: typeof import("primevue/timeline")['default']
  VirtualScroller: typeof import("primevue/virtualscroller")['default']
  Accordion: typeof import("primevue/accordion")['default']
  AccordionPanel: typeof import("primevue/accordionpanel")['default']
  AccordionHeader: typeof import("primevue/accordionheader")['default']
  AccordionContent: typeof import("primevue/accordioncontent")['default']
  AccordionTab: typeof import("primevue/accordiontab")['default']
  Card: typeof import("primevue/card")['default']
  DeferredContent: typeof import("primevue/deferredcontent")['default']
  Divider: typeof import("primevue/divider")['default']
  Fieldset: typeof import("primevue/fieldset")['default']
  Panel: typeof import("primevue/panel")['default']
  ScrollPanel: typeof import("primevue/scrollpanel")['default']
  Splitter: typeof import("primevue/splitter")['default']
  SplitterPanel: typeof import("primevue/splitterpanel")['default']
  Stepper: typeof import("primevue/stepper")['default']
  StepList: typeof import("primevue/steplist")['default']
  Step: typeof import("primevue/step")['default']
  StepItem: typeof import("primevue/stepitem")['default']
  StepPanels: typeof import("primevue/steppanels")['default']
  StepPanel: typeof import("primevue/steppanel")['default']
  TabView: typeof import("primevue/tabview")['default']
  Tabs: typeof import("primevue/tabs")['default']
  TabList: typeof import("primevue/tablist")['default']
  Tab: typeof import("primevue/tab")['default']
  TabPanels: typeof import("primevue/tabpanels")['default']
  TabPanel: typeof import("primevue/tabpanel")['default']
  Toolbar: typeof import("primevue/toolbar")['default']
  ConfirmDialog: typeof import("primevue/confirmdialog")['default']
  ConfirmPopup: typeof import("primevue/confirmpopup")['default']
  Dialog: typeof import("primevue/dialog")['default']
  Drawer: typeof import("primevue/drawer")['default']
  DynamicDialog: typeof import("primevue/dynamicdialog")['default']
  OverlayPanel: typeof import("primevue/overlaypanel")['default']
  Popover: typeof import("primevue/popover")['default']
  Sidebar: typeof import("primevue/sidebar")['default']
  FileUpload: typeof import("primevue/fileupload")['default']
  Breadcrumb: typeof import("primevue/breadcrumb")['default']
  ContextMenu: typeof import("primevue/contextmenu")['default']
  Dock: typeof import("primevue/dock")['default']
  Menu: typeof import("primevue/menu")['default']
  Menubar: typeof import("primevue/menubar")['default']
  MegaMenu: typeof import("primevue/megamenu")['default']
  PanelMenu: typeof import("primevue/panelmenu")['default']
  Steps: typeof import("primevue/steps")['default']
  TabMenu: typeof import("primevue/tabmenu")['default']
  TieredMenu: typeof import("primevue/tieredmenu")['default']
  Message: typeof import("primevue/message")['default']
  InlineMessage: typeof import("primevue/inlinemessage")['default']
  Toast: typeof import("primevue/toast")['default']
  Carousel: typeof import("primevue/carousel")['default']
  Galleria: typeof import("primevue/galleria")['default']
  Image: typeof import("primevue/image")['default']
  ImageCompare: typeof import("primevue/imagecompare")['default']
  Avatar: typeof import("primevue/avatar")['default']
  AvatarGroup: typeof import("primevue/avatargroup")['default']
  Badge: typeof import("primevue/badge")['default']
  BlockUI: typeof import("primevue/blockui")['default']
  Chip: typeof import("primevue/chip")['default']
  Inplace: typeof import("primevue/inplace")['default']
  MeterGroup: typeof import("primevue/metergroup")['default']
  OverlayBadge: typeof import("primevue/overlaybadge")['default']
  ScrollTop: typeof import("primevue/scrolltop")['default']
  Skeleton: typeof import("primevue/skeleton")['default']
  ProgressBar: typeof import("primevue/progressbar")['default']
  ProgressSpinner: typeof import("primevue/progressspinner")['default']
  Tag: typeof import("primevue/tag")['default']
  Terminal: typeof import("primevue/terminal")['default']
  Form: typeof import("@primevue/forms/form")['default']
  FormField: typeof import("@primevue/forms/formfield")['default']
  ErrorMessage: typeof import("vee-validate")['ErrorMessage']
  VeeField: typeof import("vee-validate")['Field']
  FieldArray: typeof import("vee-validate")['FieldArray']
  VeeForm: typeof import("vee-validate")['Form']
  NuxtLinkLocale: typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  SwitchLocalePathLink: typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  NuxtPage: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyAppInput: LazyComponent<typeof import("../../app/components/AppComponents/AppInput.vue")['default']>
  LazyFormDateInput: LazyComponent<typeof import("../../app/components/AppComponents/FormDateInput.vue")['default']>
  LazyHeaderCompetition: LazyComponent<typeof import("../../app/components/AppComponents/HeaderCompetition.vue")['default']>
  LazyLoader: LazyComponent<typeof import("../../app/components/AppComponents/Loader.vue")['default']>
  LazySearchBar: LazyComponent<typeof import("../../app/components/AppComponents/SearchBar.vue")['default']>
  LazyAppFooter: LazyComponent<typeof import("../../app/components/AppFooter.vue")['default']>
  LazyAuthFooter: LazyComponent<typeof import("../../app/components/Auth/AuthFooter.vue")['default']>
  LazyAuthForm: LazyComponent<typeof import("../../app/components/Auth/AuthForm.vue")['default']>
  LazyAuthHero: LazyComponent<typeof import("../../app/components/Auth/AuthHero.vue")['default']>
  LazyAuthSocial: LazyComponent<typeof import("../../app/components/Auth/AuthSocial.vue")['default']>
  LazyProfileEmpty: LazyComponent<typeof import("../../app/components/Profile/ProfileEmpty.vue")['default']>
  LazyProfileHero: LazyComponent<typeof import("../../app/components/Profile/ProfileHero.vue")['default']>
  LazyProfileHistory: LazyComponent<typeof import("../../app/components/Profile/ProfileHistory.vue")['default']>
  LazyProfileInfo: LazyComponent<typeof import("../../app/components/Profile/ProfileInfo.vue")['default']>
  LazyAdminTaskControls: LazyComponent<typeof import("../../app/components/Tasks/AdminTaskControls.vue")['default']>
  LazyCreateTaskModal: LazyComponent<typeof import("../../app/components/Tasks/CreateTaskModal.vue")['default']>
  LazyTaskAdminPanel: LazyComponent<typeof import("../../app/components/Tasks/TaskAdminPanel.vue")['default']>
  LazyTaskCard: LazyComponent<typeof import("../../app/components/Tasks/TaskCard.vue")['default']>
  LazyTaskDetailHero: LazyComponent<typeof import("../../app/components/Tasks/TaskDetailHero.vue")['default']>
  LazyTaskSidebar: LazyComponent<typeof import("../../app/components/Tasks/TaskSidebar.vue")['default']>
  LazyTaskSubmissionForm: LazyComponent<typeof import("../../app/components/Tasks/TaskSubmissionForm.vue")['default']>
  LazyTasksHero: LazyComponent<typeof import("../../app/components/Tasks/TasksHero.vue")['default']>
  LazyCreateTeamModal: LazyComponent<typeof import("../../app/components/Teams/CreateTeamModal.vue")['default']>
  LazyEditTeamModal: LazyComponent<typeof import("../../app/components/Teams/EditTeamModal.vue")['default']>
  LazyTeamCard: LazyComponent<typeof import("../../app/components/Teams/TeamCard.vue")['default']>
  LazyLanguageSwitcher: LazyComponent<typeof import("../../app/components/shared/LanguageSwitcher.vue")['default']>
  LazyCreateTournamentModal: LazyComponent<typeof import("../../app/components/tournaments/CreateTournamentModal.vue")['default']>
  LazyTournamentAbout: LazyComponent<typeof import("../../app/components/tournaments/Detail/TournamentAbout.vue")['default']>
  LazyTournamentTeamsSection: LazyComponent<typeof import("../../app/components/tournaments/Detail/TournamentTeamsSection.vue")['default']>
  LazyEditTournamentModal: LazyComponent<typeof import("../../app/components/tournaments/EditTournamentModal.vue")['default']>
  LazyTournamentBracket: LazyComponent<typeof import("../../app/components/tournaments/TournamentBracket.vue")['default']>
  LazyTournamentCard: LazyComponent<typeof import("../../app/components/tournaments/TournamentCard.vue")['default']>
  LazyTournamentHero: LazyComponent<typeof import("../../app/components/tournaments/TournamentHero.vue")['default']>
  LazyTournamentInfo: LazyComponent<typeof import("../../app/components/tournaments/TournamentInfo.vue")['default']>
  LazyTournamentJuryManager: LazyComponent<typeof import("../../app/components/tournaments/TournamentJuryManager.vue")['default']>
  LazyTournamentSidebar: LazyComponent<typeof import("../../app/components/tournaments/TournamentSidebar.vue")['default']>
  LazyTournamentStats: LazyComponent<typeof import("../../app/components/tournaments/TournamentStats.vue")['default']>
  LazyTournamentTeamsTable: LazyComponent<typeof import("../../app/components/tournaments/TournamentTeamsTable.vue")['default']>
  LazyTournamentsList: LazyComponent<typeof import("../../app/components/tournaments/TournamentsList.vue")['default']>
  LazyDeleteModal: LazyComponent<typeof import("../../app/components/tournaments/deleteModal.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtAnnouncer: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.15.3__ioredis@5.10.1_magicast@0.5.2/node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  LazyNuxtPicture: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.15.3__ioredis@5.10.1_magicast@0.5.2/node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  LazyAutoComplete: LazyComponent<typeof import("primevue/autocomplete")['default']>
  LazyCalendar: LazyComponent<typeof import("primevue/calendar")['default']>
  LazyCascadeSelect: LazyComponent<typeof import("primevue/cascadeselect")['default']>
  LazyCheckbox: LazyComponent<typeof import("primevue/checkbox")['default']>
  LazyCheckboxGroup: LazyComponent<typeof import("primevue/checkboxgroup")['default']>
  LazyChips: LazyComponent<typeof import("primevue/chips")['default']>
  LazyColorPicker: LazyComponent<typeof import("primevue/colorpicker")['default']>
  LazyDatePicker: LazyComponent<typeof import("primevue/datepicker")['default']>
  LazyDropdown: LazyComponent<typeof import("primevue/dropdown")['default']>
  LazyFloatLabel: LazyComponent<typeof import("primevue/floatlabel")['default']>
  LazyFluid: LazyComponent<typeof import("primevue/fluid")['default']>
  LazyIconField: LazyComponent<typeof import("primevue/iconfield")['default']>
  LazyIftaLabel: LazyComponent<typeof import("primevue/iftalabel")['default']>
  LazyInputChips: LazyComponent<typeof import("primevue/inputchips")['default']>
  LazyInputGroup: LazyComponent<typeof import("primevue/inputgroup")['default']>
  LazyInputGroupAddon: LazyComponent<typeof import("primevue/inputgroupaddon")['default']>
  LazyInputIcon: LazyComponent<typeof import("primevue/inputicon")['default']>
  LazyInputMask: LazyComponent<typeof import("primevue/inputmask")['default']>
  LazyInputNumber: LazyComponent<typeof import("primevue/inputnumber")['default']>
  LazyInputOtp: LazyComponent<typeof import("primevue/inputotp")['default']>
  LazyInputSwitch: LazyComponent<typeof import("primevue/inputswitch")['default']>
  LazyInputText: LazyComponent<typeof import("primevue/inputtext")['default']>
  LazyKnob: LazyComponent<typeof import("primevue/knob")['default']>
  LazyListbox: LazyComponent<typeof import("primevue/listbox")['default']>
  LazyMultiSelect: LazyComponent<typeof import("primevue/multiselect")['default']>
  LazyPassword: LazyComponent<typeof import("primevue/password")['default']>
  LazyRadioButton: LazyComponent<typeof import("primevue/radiobutton")['default']>
  LazyRadioButtonGroup: LazyComponent<typeof import("primevue/radiobuttongroup")['default']>
  LazyRating: LazyComponent<typeof import("primevue/rating")['default']>
  LazySelect: LazyComponent<typeof import("primevue/select")['default']>
  LazySelectButton: LazyComponent<typeof import("primevue/selectbutton")['default']>
  LazySlider: LazyComponent<typeof import("primevue/slider")['default']>
  LazyTextarea: LazyComponent<typeof import("primevue/textarea")['default']>
  LazyToggleButton: LazyComponent<typeof import("primevue/togglebutton")['default']>
  LazyToggleSwitch: LazyComponent<typeof import("primevue/toggleswitch")['default']>
  LazyTreeSelect: LazyComponent<typeof import("primevue/treeselect")['default']>
  LazyButton: LazyComponent<typeof import("primevue/button")['default']>
  LazyButtonGroup: LazyComponent<typeof import("primevue/buttongroup")['default']>
  LazySpeedDial: LazyComponent<typeof import("primevue/speeddial")['default']>
  LazySplitButton: LazyComponent<typeof import("primevue/splitbutton")['default']>
  LazyColumn: LazyComponent<typeof import("primevue/column")['default']>
  LazyRow: LazyComponent<typeof import("primevue/row")['default']>
  LazyColumnGroup: LazyComponent<typeof import("primevue/columngroup")['default']>
  LazyDataTable: LazyComponent<typeof import("primevue/datatable")['default']>
  LazyDataView: LazyComponent<typeof import("primevue/dataview")['default']>
  LazyOrderList: LazyComponent<typeof import("primevue/orderlist")['default']>
  LazyOrganizationChart: LazyComponent<typeof import("primevue/organizationchart")['default']>
  LazyPaginator: LazyComponent<typeof import("primevue/paginator")['default']>
  LazyPickList: LazyComponent<typeof import("primevue/picklist")['default']>
  LazyTree: LazyComponent<typeof import("primevue/tree")['default']>
  LazyTreeTable: LazyComponent<typeof import("primevue/treetable")['default']>
  LazyTimeline: LazyComponent<typeof import("primevue/timeline")['default']>
  LazyVirtualScroller: LazyComponent<typeof import("primevue/virtualscroller")['default']>
  LazyAccordion: LazyComponent<typeof import("primevue/accordion")['default']>
  LazyAccordionPanel: LazyComponent<typeof import("primevue/accordionpanel")['default']>
  LazyAccordionHeader: LazyComponent<typeof import("primevue/accordionheader")['default']>
  LazyAccordionContent: LazyComponent<typeof import("primevue/accordioncontent")['default']>
  LazyAccordionTab: LazyComponent<typeof import("primevue/accordiontab")['default']>
  LazyCard: LazyComponent<typeof import("primevue/card")['default']>
  LazyDeferredContent: LazyComponent<typeof import("primevue/deferredcontent")['default']>
  LazyDivider: LazyComponent<typeof import("primevue/divider")['default']>
  LazyFieldset: LazyComponent<typeof import("primevue/fieldset")['default']>
  LazyPanel: LazyComponent<typeof import("primevue/panel")['default']>
  LazyScrollPanel: LazyComponent<typeof import("primevue/scrollpanel")['default']>
  LazySplitter: LazyComponent<typeof import("primevue/splitter")['default']>
  LazySplitterPanel: LazyComponent<typeof import("primevue/splitterpanel")['default']>
  LazyStepper: LazyComponent<typeof import("primevue/stepper")['default']>
  LazyStepList: LazyComponent<typeof import("primevue/steplist")['default']>
  LazyStep: LazyComponent<typeof import("primevue/step")['default']>
  LazyStepItem: LazyComponent<typeof import("primevue/stepitem")['default']>
  LazyStepPanels: LazyComponent<typeof import("primevue/steppanels")['default']>
  LazyStepPanel: LazyComponent<typeof import("primevue/steppanel")['default']>
  LazyTabView: LazyComponent<typeof import("primevue/tabview")['default']>
  LazyTabs: LazyComponent<typeof import("primevue/tabs")['default']>
  LazyTabList: LazyComponent<typeof import("primevue/tablist")['default']>
  LazyTab: LazyComponent<typeof import("primevue/tab")['default']>
  LazyTabPanels: LazyComponent<typeof import("primevue/tabpanels")['default']>
  LazyTabPanel: LazyComponent<typeof import("primevue/tabpanel")['default']>
  LazyToolbar: LazyComponent<typeof import("primevue/toolbar")['default']>
  LazyConfirmDialog: LazyComponent<typeof import("primevue/confirmdialog")['default']>
  LazyConfirmPopup: LazyComponent<typeof import("primevue/confirmpopup")['default']>
  LazyDialog: LazyComponent<typeof import("primevue/dialog")['default']>
  LazyDrawer: LazyComponent<typeof import("primevue/drawer")['default']>
  LazyDynamicDialog: LazyComponent<typeof import("primevue/dynamicdialog")['default']>
  LazyOverlayPanel: LazyComponent<typeof import("primevue/overlaypanel")['default']>
  LazyPopover: LazyComponent<typeof import("primevue/popover")['default']>
  LazySidebar: LazyComponent<typeof import("primevue/sidebar")['default']>
  LazyFileUpload: LazyComponent<typeof import("primevue/fileupload")['default']>
  LazyBreadcrumb: LazyComponent<typeof import("primevue/breadcrumb")['default']>
  LazyContextMenu: LazyComponent<typeof import("primevue/contextmenu")['default']>
  LazyDock: LazyComponent<typeof import("primevue/dock")['default']>
  LazyMenu: LazyComponent<typeof import("primevue/menu")['default']>
  LazyMenubar: LazyComponent<typeof import("primevue/menubar")['default']>
  LazyMegaMenu: LazyComponent<typeof import("primevue/megamenu")['default']>
  LazyPanelMenu: LazyComponent<typeof import("primevue/panelmenu")['default']>
  LazySteps: LazyComponent<typeof import("primevue/steps")['default']>
  LazyTabMenu: LazyComponent<typeof import("primevue/tabmenu")['default']>
  LazyTieredMenu: LazyComponent<typeof import("primevue/tieredmenu")['default']>
  LazyMessage: LazyComponent<typeof import("primevue/message")['default']>
  LazyInlineMessage: LazyComponent<typeof import("primevue/inlinemessage")['default']>
  LazyToast: LazyComponent<typeof import("primevue/toast")['default']>
  LazyCarousel: LazyComponent<typeof import("primevue/carousel")['default']>
  LazyGalleria: LazyComponent<typeof import("primevue/galleria")['default']>
  LazyImage: LazyComponent<typeof import("primevue/image")['default']>
  LazyImageCompare: LazyComponent<typeof import("primevue/imagecompare")['default']>
  LazyAvatar: LazyComponent<typeof import("primevue/avatar")['default']>
  LazyAvatarGroup: LazyComponent<typeof import("primevue/avatargroup")['default']>
  LazyBadge: LazyComponent<typeof import("primevue/badge")['default']>
  LazyBlockUI: LazyComponent<typeof import("primevue/blockui")['default']>
  LazyChip: LazyComponent<typeof import("primevue/chip")['default']>
  LazyInplace: LazyComponent<typeof import("primevue/inplace")['default']>
  LazyMeterGroup: LazyComponent<typeof import("primevue/metergroup")['default']>
  LazyOverlayBadge: LazyComponent<typeof import("primevue/overlaybadge")['default']>
  LazyScrollTop: LazyComponent<typeof import("primevue/scrolltop")['default']>
  LazySkeleton: LazyComponent<typeof import("primevue/skeleton")['default']>
  LazyProgressBar: LazyComponent<typeof import("primevue/progressbar")['default']>
  LazyProgressSpinner: LazyComponent<typeof import("primevue/progressspinner")['default']>
  LazyTag: LazyComponent<typeof import("primevue/tag")['default']>
  LazyTerminal: LazyComponent<typeof import("primevue/terminal")['default']>
  LazyForm: LazyComponent<typeof import("@primevue/forms/form")['default']>
  LazyFormField: LazyComponent<typeof import("@primevue/forms/formfield")['default']>
  LazyErrorMessage: LazyComponent<typeof import("vee-validate")['ErrorMessage']>
  LazyVeeField: LazyComponent<typeof import("vee-validate")['Field']>
  LazyFieldArray: LazyComponent<typeof import("vee-validate")['FieldArray']>
  LazyVeeForm: LazyComponent<typeof import("vee-validate")['Form']>
  LazyNuxtLinkLocale: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  LazySwitchLocalePathLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
