// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.2_pinia@3.0.4_typescript@5.9.3_vue@3.5.30_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/browser-devtools-timing.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/dev-server-logs.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@pinia+nuxt@0.11.3_magicast@0.5.2_pinia@3.0.4_typescript@5.9.3_vue@3.5.30_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/pages/runtime/plugins/check-if-page-unused.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.1_@types+node@22.15.3_jiti@2.6.1_lightningcss@1.32.0_sass@1.98._iisz6voh7j4nmjutsqrnxsvx5i/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxt+devtools@3.2.4_vite@7.3.1_@types+node@22.15.3_jiti@2.6.1_lightningcss@1.32.0_sass@1.98._iisz6voh7j4nmjutsqrnxsvx5i/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/switch-locale-path-ssr.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/route-locale-detect.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/preload.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/dev.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/i18n.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@primevue+nuxt-module@4.5.4_@babel+parser@8.0.0-rc.5_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/@primevue/nuxt-module/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/warn.dev.server.js")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-proposal-decorators@7.29.0_@babel+core@7.29.0__@b_nkp74coksl4apnfsn3tjagqmpe/node_modules/nuxt/dist/app/plugins/check-if-layout-used.js")> &
  InjectionType<typeof import("../../app/plugins/api")> &
  InjectionType<typeof import("../../app/plugins/axios")> &
  InjectionType<typeof import("../../app/plugins/toast.client")> &
  InjectionType<typeof import("../../app/plugins/vee-validate")> &
  InjectionType<typeof import("../../../../node_modules/.pnpm/@nuxtjs+i18n@10.3.0_@vue+compiler-dom@3.5.30_db0@0.3.4_@electric-sql+pglite@0.3.15_mysql2@3.1_qr4sn6o2k5vcnvc7mlir5io7fa/node_modules/@nuxtjs/i18n/dist/runtime/plugins/ssg-detect.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'vue-devtools-client' | 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:browser-devtools-timing' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | 'nuxt:checkIfPageUnused' | 'i18n:plugin:switch-locale-path-ssr' | 'i18n:plugin:route-locale-detect' | 'i18n:plugin:preload' | 'i18n:dev' | 'i18n:plugin' | 'nuxt:checkIfLayoutUsed' | 'i18n:plugin:ssg-detect'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
